create extension if not exists pgcrypto;

create table if not exists public.team_rooms (id uuid primary key default gen_random_uuid(), name text not null check (char_length(name) between 1 and 80), owner_id uuid not null references auth.users(id), created_at timestamptz not null default now());
create table if not exists public.team_room_members (room_id uuid not null references public.team_rooms(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null check (role in ('owner','member')), joined_at timestamptz not null default now(), primary key (room_id,user_id));
create table if not exists public.team_room_invites (room_id uuid primary key references public.team_rooms(id) on delete cascade, code_hash text not null, expires_at timestamptz not null, created_at timestamptz not null default now());
create table if not exists public.team_room_files (id uuid primary key default gen_random_uuid(), room_id uuid not null references public.team_rooms(id) on delete cascade, name text not null, yaml_content text not null, updated_by uuid not null references auth.users(id), updated_at timestamptz not null default now(), unique(room_id,name));

alter table public.team_rooms enable row level security; alter table public.team_room_members enable row level security; alter table public.team_room_invites enable row level security; alter table public.team_room_files enable row level security;
create or replace function public.is_team_room_member(target_room_id uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists (select 1 from public.team_room_members where room_id=target_room_id and user_id=auth.uid()) $$;
grant execute on function public.is_team_room_member(uuid) to authenticated;
create policy "members read rooms" on public.team_rooms for select using (public.is_team_room_member(id));
create policy "members read memberships" on public.team_room_members for select using (public.is_team_room_member(room_id));
create policy "members read files" on public.team_room_files for select using (public.is_team_room_member(room_id));
create policy "members write files" on public.team_room_files for all using (public.is_team_room_member(room_id)) with check (auth.uid()=updated_by and public.is_team_room_member(room_id));

create or replace function public.list_team_rooms() returns table (id uuid, name text, owner_id uuid, member_count bigint, role text) language sql security definer set search_path=public as $$ select r.id,r.name,r.owner_id,count(m2.user_id),m.role from team_room_members m join team_rooms r on r.id=m.room_id join team_room_members m2 on m2.room_id=r.id where m.user_id=auth.uid() group by r.id,m.role $$;
create or replace function public.create_team_room(room_name text) returns jsonb language plpgsql security definer set search_path=public as $$ declare room team_rooms; code text:=lpad(floor(random()*10000)::text,4,'0'); begin insert into team_rooms(name,owner_id) values(trim(room_name),auth.uid()) returning * into room; insert into team_room_members values(room.id,auth.uid(),'owner'); insert into team_room_invites values(room.id,extensions.crypt(code,extensions.gen_salt('bf')),now()+interval '24 hours'); return jsonb_build_object('id',room.id,'name',room.name,'owner_id',room.owner_id,'member_count',1,'role','owner','invite_code',code); end $$;
create or replace function public.join_team_room(invite_code text) returns jsonb language plpgsql security definer set search_path=public as $$ declare invite team_room_invites; room team_rooms; count_members bigint; begin select * into invite from team_room_invites where expires_at>now() and extensions.crypt(invite_code,code_hash)=code_hash; if invite.room_id is null then raise exception 'That invite code is invalid or expired'; end if; insert into team_room_members values(invite.room_id,auth.uid(),'member') on conflict do nothing; select * into room from team_rooms where id=invite.room_id; select count(*) into count_members from team_room_members where room_id=room.id; return jsonb_build_object('id',room.id,'name',room.name,'owner_id',room.owner_id,'member_count',count_members,'role','member'); end $$;
grant execute on function public.list_team_rooms(),public.create_team_room(text),public.join_team_room(text) to authenticated;
